"""D23's copy-generation and approval endpoints under ``/admin``.

``POST /variants/{variant_id}/content-drafts`` enqueues generation for one
``(variant, channel, locale)`` — see
``features.content.generate_content_draft``'s docstring for why the
trigger is manual (caller-supplied ``channel``/``locale``) rather than
auto-derived from an approval event. Returns ``202`` — this only writes an
outbox event; nothing has been generated by the time the response is sent.

``POST /content/generate-next`` is the worker step, the same
"claims whatever job is oldest-due for the tenant, no resource id, no
automatic trigger yet" shape ``POST .../generation/render-next`` and
``POST .../generation/qc-next`` already use. Gated on the same
``Capability.PRODUCT_MANAGE`` those routes use, not ``CATALOG_APPROVE`` —
this is generation-pipeline work, not an approval action.

``GET /variants/{variant_id}/content-drafts`` (live drafts for a variant),
``POST /content-drafts/{id}/approve`` and ``POST /content-drafts/{id}/reject``
are the approval-gate half — gated on ``Capability.CATALOG_APPROVE``, the
**same** capability ``admin_catalog_images.py`` uses for imagery. Not a new
``CONTENT_APPROVE`` capability: D23 says copy is subject to "the same
approval gate as imagery," and ``catalog.approve`` already reads as
"approve catalog content" broadly — an approver who can approve an image
but not its caption is a distinction nothing in this codebase has asked
for. `list_for_variant`` (not a cursor-paginated ``list_page`` — no
multi-variant queue view exists yet, unlike the images queue) is filtered
to live rows here, in the router, rather than adding a port method for a
single caller.

``PATCH /content-drafts/{id}`` is manual copy editing — gated on
``Capability.PRODUCT_MANAGE``, matching the generation route above, not
``CATALOG_APPROVE``: writing copy is content authoring, the same
capability that triggers generation, regardless of who later approves it.
See `features.content.edit_content_draft`'s docstring for why an edit
re-runs both the forbidden-claims check and the approval gate rather than
trusting the editor.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, status
from pydantic import BaseModel

from app.api.deps.authorization import PrincipalDep, require_capability
from app.bootstrap.di import (
    ApproveContentDraftDep,
    CopywritingAgentDep,
    EditContentDraftDep,
    GenerateContentDraftDep,
    ListContentDraftsForVariantDep,
    RejectContentDraftDep,
)
from app.entities.capabilities import Capability
from app.entities.content_draft import ContentDraft
from app.shared.ids import ContentDraftId, ProductVariantId, UserId

router = APIRouter()
_manage = [Depends(require_capability(Capability.PRODUCT_MANAGE))]
_approve = [Depends(require_capability(Capability.CATALOG_APPROVE))]


class GenerateContentDraftRequest(BaseModel):
    channel: str
    locale: str


class GenerateContentDraftAck(BaseModel):
    variant_id: ProductVariantId
    channel: str
    locale: str


@router.post(
    "/variants/{variant_id}/content-drafts",
    response_model=GenerateContentDraftAck,
    status_code=status.HTTP_202_ACCEPTED,
    dependencies=_manage,
)
async def generate_content_draft(
    variant_id: ProductVariantId,
    body: GenerateContentDraftRequest,
    principal: PrincipalDep,
    use_case: GenerateContentDraftDep,
) -> GenerateContentDraftAck:
    assert principal.tenant_id is not None
    await use_case(
        tenant_id=principal.tenant_id,
        variant_id=variant_id,
        channel=body.channel,
        locale=body.locale,
    )
    return GenerateContentDraftAck(variant_id=variant_id, channel=body.channel, locale=body.locale)


class ContentDraftResponse(BaseModel):
    id: ContentDraftId
    variant_id: ProductVariantId
    channel: str
    locale: str
    title: str | None
    body: str
    hashtags: list[str]
    cta: str | None
    alt_text: str
    status: str
    edited_by: UserId | None
    approved_by: UserId | None
    rejection_reason: str | None
    created_at: datetime

    @staticmethod
    def from_entity(d: ContentDraft) -> ContentDraftResponse:
        return ContentDraftResponse(
            id=d.id,
            variant_id=d.variant_id,
            channel=d.channel,
            locale=d.locale,
            title=d.title,
            body=d.body,
            hashtags=d.hashtags,
            cta=d.cta,
            alt_text=d.alt_text,
            status=d.status.value,
            edited_by=d.edited_by,
            approved_by=d.approved_by,
            rejection_reason=d.rejection_reason,
            created_at=d.created_at,
        )


@router.post(
    "/content/generate-next", response_model=ContentDraftResponse | None, dependencies=_manage
)
async def generate_next_content_draft(
    principal: PrincipalDep, agent: CopywritingAgentDep
) -> ContentDraftResponse | None:
    assert principal.tenant_id is not None
    draft = await agent.run(tenant_id=principal.tenant_id)
    return ContentDraftResponse.from_entity(draft) if draft is not None else None


@router.get(
    "/variants/{variant_id}/content-drafts",
    response_model=list[ContentDraftResponse],
    dependencies=_approve,
)
async def list_content_drafts_for_variant(
    variant_id: ProductVariantId,
    principal: PrincipalDep,
    use_case: ListContentDraftsForVariantDep,
) -> list[ContentDraftResponse]:
    assert principal.tenant_id is not None
    drafts = await use_case(tenant_id=principal.tenant_id, variant_id=variant_id)
    return [ContentDraftResponse.from_entity(d) for d in drafts]


@router.post(
    "/content-drafts/{draft_id}/approve", response_model=ContentDraftResponse, dependencies=_approve
)
async def approve_content_draft(
    draft_id: ContentDraftId, principal: PrincipalDep, use_case: ApproveContentDraftDep
) -> ContentDraftResponse:
    assert principal.tenant_id is not None
    draft = await use_case(
        tenant_id=principal.tenant_id, draft_id=draft_id, approved_by=principal.user_id
    )
    return ContentDraftResponse.from_entity(draft)


class RejectContentDraftRequest(BaseModel):
    reason: str


@router.post(
    "/content-drafts/{draft_id}/reject", response_model=ContentDraftResponse, dependencies=_approve
)
async def reject_content_draft(
    draft_id: ContentDraftId,
    body: RejectContentDraftRequest,
    principal: PrincipalDep,
    use_case: RejectContentDraftDep,
) -> ContentDraftResponse:
    assert principal.tenant_id is not None
    draft = await use_case(
        tenant_id=principal.tenant_id,
        draft_id=draft_id,
        reason=body.reason,
        rejected_by=principal.user_id,
    )
    return ContentDraftResponse.from_entity(draft)


class EditContentDraftRequest(BaseModel):
    title: str | None = None
    body: str
    hashtags: list[str] = []
    cta: str | None = None
    alt_text: str


@router.patch(
    "/content-drafts/{draft_id}", response_model=ContentDraftResponse, dependencies=_manage
)
async def edit_content_draft(
    draft_id: ContentDraftId,
    body: EditContentDraftRequest,
    principal: PrincipalDep,
    use_case: EditContentDraftDep,
) -> ContentDraftResponse:
    assert principal.tenant_id is not None
    draft = await use_case(
        tenant_id=principal.tenant_id,
        draft_id=draft_id,
        edited_by=principal.user_id,
        title=body.title,
        body=body.body,
        hashtags=body.hashtags,
        cta=body.cta,
        alt_text=body.alt_text,
    )
    return ContentDraftResponse.from_entity(draft)
