"""D23's copy-generation endpoints under ``/admin``.

``POST /variants/{variant_id}/content-drafts`` enqueues generation for one
``(variant, channel, locale)`` — see
``features.content.generate_content_draft``'s docstring for why the
trigger is manual (caller-supplied ``channel``/``locale``) rather than
auto-derived from an approval event. Returns ``202`` — this only writes an
outbox event; nothing has been generated by the time the response is sent.

``POST /content/generate-next`` is the worker step, the same
"claims whatever job is oldest-due for the tenant, no resource id, no
automatic trigger yet" shape ``POST .../generation/render-next`` and
``POST .../generation/qc-next`` already use. Gated on the same
``Capability.PRODUCT_MANAGE`` those routes use, not ``CATALOG_APPROVE`` —
this is generation-pipeline work, not an approval action.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, status
from pydantic import BaseModel

from app.api.deps.authorization import PrincipalDep, require_capability
from app.bootstrap.di import CopywritingAgentDep, GenerateContentDraftDep
from app.entities.capabilities import Capability
from app.entities.content_draft import ContentDraft
from app.shared.ids import ContentDraftId, ProductVariantId

router = APIRouter()
_manage = [Depends(require_capability(Capability.PRODUCT_MANAGE))]


class GenerateContentDraftRequest(BaseModel):
    channel: str
    locale: str


class GenerateContentDraftAck(BaseModel):
    variant_id: ProductVariantId
    channel: str
    locale: str


@router.post(
    "/variants/{variant_id}/content-drafts",
    response_model=GenerateContentDraftAck,
    status_code=status.HTTP_202_ACCEPTED,
    dependencies=_manage,
)
async def generate_content_draft(
    variant_id: ProductVariantId,
    body: GenerateContentDraftRequest,
    principal: PrincipalDep,
    use_case: GenerateContentDraftDep,
) -> GenerateContentDraftAck:
    assert principal.tenant_id is not None
    await use_case(
        tenant_id=principal.tenant_id,
        variant_id=variant_id,
        channel=body.channel,
        locale=body.locale,
    )
    return GenerateContentDraftAck(variant_id=variant_id, channel=body.channel, locale=body.locale)


class ContentDraftResponse(BaseModel):
    id: ContentDraftId
    variant_id: ProductVariantId
    channel: str
    locale: str
    title: str | None
    body: str
    hashtags: list[str]
    cta: str | None
    alt_text: str
    status: str
    created_at: datetime

    @staticmethod
    def from_entity(d: ContentDraft) -> ContentDraftResponse:
        return ContentDraftResponse(
            id=d.id,
            variant_id=d.variant_id,
            channel=d.channel,
            locale=d.locale,
            title=d.title,
            body=d.body,
            hashtags=d.hashtags,
            cta=d.cta,
            alt_text=d.alt_text,
            status=d.status.value,
            created_at=d.created_at,
        )


@router.post(
    "/content/generate-next", response_model=ContentDraftResponse | None, dependencies=_manage
)
async def generate_next_content_draft(
    principal: PrincipalDep, agent: CopywritingAgentDep
) -> ContentDraftResponse | None:
    assert principal.tenant_id is not None
    draft = await agent.run(tenant_id=principal.tenant_id)
    return ContentDraftResponse.from_entity(draft) if draft is not None else None
