"""add publications

Revision ID: e37248aeeee4
Revises: 2daa149ded1f
Create Date: 2026-08-15 03:10:00.000000

D21's Gate-critical table — the one that makes the "a retry after a
timeout does not create a second post" test provable at all.
``idempotency_key`` is generated once, at ``Publication.create()`` time,
and never regenerated by a retry: ``UNIQUE (tenant_id, idempotency_key)``
is the database's own backstop on that invariant, even though the real
protection is architectural (the key is committed in one transaction, the
provider call happens in a later, independent one — see
``features.publishing.create_publication``'s docstring).

Unlike ``catalog_images``/``content_drafts``, this table is **not** a
current-state-plus-``superseded_by`` design. A publication is one specific
post; retrying it is the same logical post trying again, not a new piece
of content replacing an old one — there is nothing here for a self-FK to
supersede. ``attempts``/``last_error`` live directly on this one mutable
row for exactly that reason, matching D21's own schema sketch rather than
delegating retry bookkeeping entirely to ``task_queue_jobs`` the way
``generation_items``/``catalog_images`` do — a merchant looking at their
publish history needs "3 attempts, last error: rate limited" on the
publication itself, not a cross-reference into an internal queue table.

Caveat worth stating plainly: ``attempts`` counts *worker-observed*
attempts (``FailPublicationPublish`` increments it once per failed
``ChannelPublisher`` call), not ``task_queue_jobs.attempts``. The stuck-job
reaper (D19) calls ``TaskQueue.fail`` directly, bypassing
``FailPublicationPublish`` entirely, so a reaped job's queue-level attempt
count can advance without this column moving — the two can legitimately
disagree after a reaper sweep. Not a bug to fix here; a reader of this
column should know it can lag, not assume it is authoritative for retry
accounting the way ``task_queue_jobs.attempts`` is.

``last_error`` also carries **non-error deferral reasons** — a per-account
rate-limit rejection (``features.publishing.defer_publication_publish``)
sets it without incrementing ``attempts`` or failing the row, since a rate
limit is "not yet," not "this failed." A reader should not assume every
populated ``last_error`` describes a genuine failure.

``channel_id`` is a composite FK into ``social_accounts`` — publishing
targets a specific *connected account*, not a bare provider name.
``content_draft_id`` is nullable: D23's copy pipeline is optional per
channel (the ``website`` adapter, for instance, may not need generated
captions at all), so a publication must be constructible without one.

``payload`` is the full composed request (caption, media asset ids, link)
at the time this row was created — the same "record what was actually
sent" reproducibility ``generation_items.prompt_rendered`` already
established, not something reconstructed from ``content_drafts`` after the
fact (the draft could be superseded by then).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from migrations.rls import create_tenant_isolation_policy, enable_rls, grant_to_app_role
from sqlalchemy.dialects import postgresql

revision: str = "e37248aeeee4"
down_revision: str | None = "2daa149ded1f"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_STATUSES = ("pending", "publishing", "published", "failed")


def upgrade() -> None:
    op.create_table(
        "publications",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("content_draft_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_post_id", sa.Text(), nullable=True),
        sa.Column("permalink", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "variant_id"],
            ["product_variants.tenant_id", "product_variants.id"],
            name="fk_publications_variant",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["social_accounts.tenant_id", "social_accounts.id"],
            name="fk_publications_channel",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "content_draft_id"],
            ["content_drafts.tenant_id", "content_drafts.id"],
            name="fk_publications_content_draft",
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_publications_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_publications_tenant_idempotency_key"
        ),
        sa.CheckConstraint(
            "status IN ('" + "','".join(_STATUSES) + "')",
            name="ck_publications_status",
        ),
    )
    op.create_index("ix_publications_tenant_id", "publications", ["tenant_id"])

    enable_rls("publications")
    create_tenant_isolation_policy("publications")
    grant_to_app_role("publications")


def downgrade() -> None:
    op.drop_table("publications")
