"""Finishes a successful render: registers the provider's bytes as a
`generated` Asset (D17's kind that "is written directly by internal
pipeline code, never by a browser upload" — see `entities.asset`), marks
the `generation_item` `succeeded`, and writes the corresponding
`catalog_images` row — `pending_qc`, D18's mutable current-state row, via
the same two-write supersede-or-create transaction `entities.catalog_image`
documents (retire the existing live row first, only then insert the
replacement, because of the deferrable FK). Completes the `task_queue` job
last, once every domain write in this transaction has succeeded.

Sniffs the real mime/dimensions from the bytes with `inspect_image` rather
than trusting anything the provider claims about its own output — the same
"never trust the caller's declared type" posture `VerifyAndRegisterUpload`
uses for a human upload. Dedups by `(tenant_id, sha256, kind)` the same way
too: a provider that returns identical bytes for two attempts (same seed,
same prompt) collapses to one `generated` asset rather than two.

`object_storage.write` happens *before* the transaction opens, not inside
it — CLAUDE.md's own external-call rule, the one `agents.generation_render`
was built around: a real bucket PUT is a multi-second network call, and
holding it inside an open transaction (right as this same transaction is
about to touch `catalog_images`' contended partial unique index) is worse
than the alternative. The dedup check only runs once a transaction is open
and can see other rows, so the ordering is necessarily write-then-check,
not check-then-write. When dedup finds an existing asset, the bytes just
written are an orphaned duplicate — deleted inside the transaction, the
same "delete on dedup" moment `VerifyAndRegisterUpload` uses (that call is
storage-only, not a second write to a contended index, so it does not carry
the same cost this docstring is warning about).

Does not run `ContentModerationScanner` against the generated bytes —
brand-safety/content checks on a generated image are D20's QC agent's job
(not built yet), a distinct concern from the upload-time moderation
`VerifyAndRegisterUpload` runs against human-submitted photos before they
ever reach this pipeline as reference material.

`variant_id` isn't on `GenerationItem` itself (it belongs to the
`generation_request` the item was fanned out from), so this loads the
parent request to get it — the same one-extra-lookup shape
`FanOutGenerationItems` already pays to reach a request's `variant_id`.
"""

from __future__ import annotations

import hashlib
from uuid import UUID

from app.entities.asset import Asset, AssetKind
from app.entities.catalog_image import CatalogImage
from app.entities.generation_item import GenerationItem
from app.services.image_inspection import inspect_image
from app.services.ports.object_storage import ObjectStorage
from app.services.ports.unit_of_work import UnitOfWorkFactory
from app.shared.clock import Clock
from app.shared.errors import NotFoundError
from app.shared.ids import GenerationItemId, TenantId

_EXTENSION_FOR_MIME = {"image/jpeg": "jpg", "image/png": "png", "image/webp": "webp"}


class CompleteGenerationItemRender:
    def __init__(
        self, uow_factory: UnitOfWorkFactory, object_storage: ObjectStorage, clock: Clock
    ) -> None:
        self._uow_factory = uow_factory
        self._object_storage = object_storage
        self._clock = clock

    async def __call__(
        self,
        *,
        tenant_id: TenantId,
        item_id: GenerationItemId,
        job_id: UUID,
        image_bytes: bytes,
        cost_micros: int,
        latency_ms: int,
    ) -> GenerationItem:
        inspection = inspect_image(image_bytes)
        sha256 = hashlib.sha256(image_bytes).hexdigest()
        storage_key = self._object_storage.new_storage_key(
            tenant_id,
            kind=AssetKind.GENERATED.value,
            extension=_EXTENSION_FOR_MIME[inspection.mime],
        )
        await self._object_storage.write(storage_key, image_bytes)

        now = self._clock.now()
        async with self._uow_factory(tenant_id) as uow:
            item = await uow.generation_items.get(tenant_id, item_id)
            if item is None:
                raise NotFoundError("Generation item not found.")

            request = await uow.generation_requests.get(tenant_id, item.request_id)
            if request is None:
                raise NotFoundError("Generation request not found.")

            asset = await uow.assets.get_by_sha256(tenant_id, sha256, AssetKind.GENERATED)
            if asset is None:
                asset = Asset.create(
                    tenant_id,
                    storage_key=storage_key,
                    sha256=sha256,
                    mime=inspection.mime,
                    width=inspection.width,
                    height=inspection.height,
                    bytes_=len(image_bytes),
                    kind=AssetKind.GENERATED,
                    source="generation",
                    now=now,
                )
                await uow.assets.add(asset)
            else:
                await self._object_storage.delete(storage_key)

            item.mark_succeeded(
                output_asset_id=asset.id, cost_micros=cost_micros, latency_ms=latency_ms
            )
            await uow.generation_items.update(item)

            live = await uow.catalog_images.get_live(
                tenant_id, request.variant_id, item.catalog_image_slot_id
            )
            new_image = CatalogImage.create(
                tenant_id,
                request.variant_id,
                item.catalog_image_slot_id,
                asset.id,
                item.id,
                now=now,
            )
            if live is not None:
                live.mark_superseded(by=new_image.id, now=now)
                await uow.catalog_images.update(live)
            await uow.catalog_images.add(new_image)

            await uow.task_queue.complete(tenant_id, job_id, now=now)

            await uow.audit_log.record(
                tenant_id,
                actor_user_id=None,
                action="generation_item.succeeded",
                subject_type="generation_item",
                subject_id=item.id,
                before=None,
                after={"catalog_image_id": str(new_image.id), "asset_id": str(asset.id)},
                now=now,
            )

            return item
